#!/bin/bash

set -eu

export TERM=linux

apt-get -y install ajaxterm byobu

configure_byobu() {
  echo "byobu byobu/launch-by-default boolean true" | debconf-set-selections
  dpkg-reconfigure -phigh byobu

  # Update byobu profile; needs a whitespace at the end of the last line for ajaxterm (?)
  sed -i -e "s/^\(hardstatus .*\)'/\1 '/" /usr/share/byobu/profiles/common
}
configure_byobu

configure_ajaxterm() {
  # Update ajaxterm configuration
  # Most web browsers can do a little better than 80x25; bump to 160x40
  sed -i -e "s/^width=.*/width=160;/" -e "s/^height=.*/height=40;/" /etc/ajaxterm.conf
  service ajaxterm restart
}
configure_ajaxterm

enable_ssh_passwords() {
  sed -i 's/PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
  service ssh restart
}
enable_ssh_passwords

configure_apache() {
  h=`unit-get public-address`
  echo "<meta http-equiv='refresh' content='0;url=https://$h/'>" > /var/www/index.html

  sed -i -e "s/__HOSTNAME__/$h/" /var/www/index.html

  a2enmod proxy_http
  a2enmod ssl
  a2ensite default-ssl
  make-ssl-cert generate-default-snakeoil --force-overwrite
  sed -i -e 's=^</VirtualHost>=  ProxyRequests Off\n  ProxyPass / http://localhost:8022/\n  ProxyPassReverse / http://localhost:8022/ \n</VirtualHost>=' /etc/apache2/sites-enabled/000-default
  sed -i -e 's=^</VirtualHost>=  ProxyRequests Off\n  ProxyPass / http://localhost:8022/\n  ProxyPassReverse / http://localhost:8022/ \n</VirtualHost>=' /etc/apache2/sites-enabled/default-ssl
  service apache2 restart
}
configure_apache

add_user() {

  echo "
  PasswordAuthentication yes
  AllowTcpForwarding no
  Match User guest
    ForceCommand exec screen -x ubuntu/byobu-classroom
  " >> /etc/ssh/sshd_config
  service ssh restart
  
  cryptpw="ubXWbZ4Ffn.mg"		# password is 'guest'
  useradd -m -s /bin/bash -p "$cryptpw" guest
  touch "/home/guest/.screenrc"
  chown -R root:root /home/guest
  dpkg-statoverride --add root root 6755 /usr/bin/screen
  chmod 6755 /usr/bin/screen
  chmod 755 /var/run/screen
  service screen-cleanup start

  # Start the shared session
  # This line should go away, once this file releases with the next byobu
  [ -f /usr/share/byobu/profiles/classroom ] || echo "
  aclumask guest+r guest-w guest-x
  aclchg guest +r-w-x '#?'
  aclchg guest +x 'detach'
  multiuser on
  escape "^Bb"
  " > /usr/share/byobu/profiles/classroom
  chmod 644 /usr/share/byobu/profiles/classroom

}
add_user

install_juju() {
  apt-add-repository ppa:juju/pkgs
  apt-get update
  apt-get -qq install -y juju charm-tools apt-cacher-ng zookeeper libvirt-bin lxc charm-helper-sh
}
install_juju

configure_juju_local_provider() {
  mkdir -p /home/ubuntu/.juju
  cat > /home/ubuntu/.juju/environments.yaml <<EOF
environments:
  local:
    type: local
    data-dir: /tmp/juju-local
    admin-secret: abcdefghijklmnopqrstuvwxyz1234567890
    control-bucket: foo-bucket
    default-series: oneiric
EOF
  chown -Rf ubuntu.ubuntu /home/ubuntu/.juju
}
configure_juju_local_provider 

generate_ssh_keys() {
  su -l ubuntu -c "ssh-keygen -q -N '' -t rsa -b 2048 -f /home/ubuntu/.ssh/id_rsa"
}
[ -f /home/ubuntu/.ssh/id_rsa ] || generate_ssh_keys

# Launch the nested screen session (byobu running inside of screen)
#su -l ubuntu -c 'screen -c /usr/share/byobu/profiles/classroom -d -m -S byobu-classroom -t class byobu -S byobu-inner bash'
su -l ubuntu -c 'screen -c /usr/share/byobu/profiles/classroom -d -m -S byobu-classroom '

open-port 443/TCP
open-port 80/TCP
