#!/bin/sh
#
#    website-relation-joined
#    Copyright (C) 2011 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Try to use metadata for a public IP; but fall back to local processing
if ! ip=$(wget -q -O- http://169.254.169.254/latest/meta-data/public-ipv4); then
	interface=$(awk 'END {print $1}' /proc/net/route)
	ip=$(LC_ALL=C /sbin/ip -4 addr list dev "$interface" scope global)
	ip=${ip#* inet }
	ip=${ip%%/*}
fi

# Try to use metadata for a public hostname; but fall back to local processing
if ! h=$(wget -q -O- http://169.254.169.254/latest/meta-data/public-hostname); then
	h=$(hostname -s)
fi

relation-set ip="$ip" port=443 hostname="$h" url="https://$h"
